eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce
          jwk-set-uri: http://keycloak:8080/realms/ecommerce/protocol/openid-connect/certs